# Generated by Django 4.0.5 on 2022-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_likes_post_snipit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snipit',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='No snippet available'),
        ),
    ]
